name:                Learning
version:             0.0.2
github:              "masterdezign/Learning"
license:             BSD3
author:              "Bogdan Penkovsky"
maintainer:          "dev at penkovsky [dot] com"
copyright:           "Bogdan Penkovsky"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Most frequently used machine learning tools
category:            Machine Learning

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/masterdezign/Learning#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- hmatrix >= 0.18.0.0
- vector

library:
  source-dirs: src

executables:
  learning-pca:
    main:                MainPCA.lhs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Learning

  learning-pca-advanced:
    main:                MainPCA2.lhs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Learning

tests:
  Learning-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Learning
